#!/bin/bash

###################################################################################
####################  NO CHANGES FOR THIS PART OF THE BATCH #######################
###################################################################################

#SBATCH --partition main            ### Specify partition name where to run a job.
#SBATCH --time 0-00:05:00           ### Job running time limit. Make sure it is not exceeding the partition time limit! Format: D-H:MM:SS
#SBATCH --output job-%J.out         ### Output log for running job - %J is the job number variable
##SBATCH --mail-user=user@post.jce.ac.il  ### User's email for sending job status
##SBATCH --mail-type=ALL            ### Conditions when to send the email. ALL,BEGIN,END,FAIL, REQUEU, NONE
#SBATCH --gres=gpu:1                ### number of GPUs, ask for more than 1 only if you can parallelize your code for multi GPU
#SBATCH --cpus-per-task=1           ### number of CPU cores

###################################################################################
####################  Start your code below #######################################
###################################################################################

#SBATCH --ntasks=9                  ### Total number of tasks/processes
#SBATCH --job-name 'Cartesian'      ### Name of the job. replace my_job with your desired job name
module load anaconda                ### load anaconda module (must present when working with conda environments)
source activate myenv               ### activating environment, environment must be configured before running the job

### Compile your program ###
mpicxx Cartesian.c -o Cartesian

### Run your program ###
mpirun ./Cartesian
